### ISSUE TITLE
Bot reloads website for every password try

### ISSUE THREAD

**Issue by jarrett-g** [royalPanic/MSCHF-Man#8]
Currently, the bot reloads the webpage every single time a password is attempted. Is there a way we can keep the page loaded? This would also theoretically bypass the new loading screen that MSCHF put on all their drops.

**Comment by royalPanic** [comment]
I don't actually know how to set up selenium to not reload the page with every new instance. I'm sure that it's possible, but I worry of the consequences of putting so many attempts through the same session.

**Comment by royalPanic** [comment]
Resolved by the rewrite.
